### ISSUE TITLE
Create/design a welcome email to send to interested users

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#10]
When users visit the website there will be a basic contact form for them to submit their email for updates from SetLife. They should receive an email after submitting this form that explains what they can expect to be updated on as well as an option to Unsubscribe.

**Comment by sofiarm21** [comment]
welcome mail design
![Mail subscription design](https://user-images.githubusercontent.com/49292858/69444119-11656f00-0d26-11ea-944d-283711ba3249.png)
https://drive.google.com/drive/folders/1CXVjtO-dHXMB4JQElkHG9KMvXKQvNMLx

**Comment by otech47** [comment]
Related to #86
