### ISSUE TITLE
Translate the Contributing guide to Spanish

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#119]
https://github.com/setlife-network/website/blob/develop/CONTRIBUTING.md

**Comment by natastro** [comment]
I'd be happy to do the spanish translation if needed. Thank you!

**Comment by otech47** [comment]
Hi @natastro thanks a lot for the comment! The workflow is literally the exact thing to be translated so I suppose you have all the info you need? When you have the translation ready just follow the Contributing guide and add the new file in the directory `/docs/es/CONTRIBUTING.md` folder to open the PR (@vikilafarga can probably do the review)

Could be nice to add a link to the Spanish version from CONTRIBUTING.md too for convenience. Leave a comment if you need anything else!

**Comment by natastro** [comment]
Thanks @otech47 ! I do have one quick question - I don't see an 'es' folder within docs. Is it okay to go ahead and create this and submit in my PR? If not just let me know 😄

**Comment by otech47** [comment]
Yes exactly you'd create the folder and we can put other Spanish docs in there in the future. Thanks!
