### ISSUE TITLE
Refresh UI newsletter tile

### ISSUE THREAD

**Issue by sofiarm21** [setlife-network/website#126]
<img width="802" alt="Screen Shot 2020-12-03 at 11 42 49 PM" src="https://user-images.githubusercontent.com/49292858/101119254-540c8900-35c1-11eb-8a96-aa10e59d3001.png">

**Comment by sofiarm21** [comment]
<img width="1440" alt="Screen Shot 2020-12-04 at 12 37 54 AM" src="https://user-images.githubusercontent.com/49292858/101122534-1f043480-35c9-11eb-8382-10a894c0cd70.png">

@otech47 any recommendation here?

**Comment by otech47** [comment]
> <img alt="Screen Shot 2020-12-04 at 12 37 54 AM" width="1440" src="https://user-images.githubusercontent.com/49292858/101122534-1f043480-35c9-11eb-8382-10a894c0cd70.png">
> 
> @otech47 any recommendation here?

@sofiarm21 yeah I think it looks good! Maybe a tiny bit more spacing between tiles and make sure they have `cursor: pointer` to appear clickable since they look like material cards and that's a pretty standard UIUX pattern then probably good to merge!

**Comment by otech47** [comment]
Duplicate/merge with #114
