### ISSUE TITLE
Deploy app to Heroku

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#29]

**Comment by sofiarm21** [comment]
Deployed website.

**Comment by sofiarm21** [comment]
**ERROR:**

Only let's me push master branch. 

Following the official documentation 

> If you want to deploy code to Heroku from a non-master branch of your local repository (for example, testbranch), use the following syntax to ensure it is pushed to the remote’s master branch:`$ git push heroku testbranch:master`

[https://devcenter.heroku.com/articles/git](url)

Console input:
`$ git push heroku develop:master`

Console output:
`error: src refspec develop does not match any.`
`error: failed to push some refs to 'https://git.heroku.com/setlife-website.git'`

**Comment by otech47** [comment]
https://setlife-website.herokuapp.com/
