### ISSUE TITLE
Set up development environment

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#3]

**Comment by sofiarm21** [comment]
pull request created, waiting for review

**Comment by otech47** [comment]
@sofiarm21 there’s a nice way to link pull requests with issues by adding something to any of the commit messages inside the PR. If you put “closes #3” in the commit message then GitHub will automatically make the link and as soon as it gets merged it will close the issue. This is good for tracking which commits and pull requests close issues and in the future we can go back and review the related code if needed
