### ISSUE TITLE
Enable Spanish translated version of the landing page

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#32]
- [x] Figure out how to detect the country or locale of the browser 
- [x] Add logic to render different constants for the Spanish speaking locale so we can show all the copy in its Spanish translated version
- [x] Explore a manual English/Spanish translate toggle

**Comment by otech47** [comment]
@sofiarm21 please look up basic designs for this so we have a clear picture of where it should go

**Comment by otech47** [comment]
Some ideas here: https://dribbble.com/search/navigation%20language

**Comment by vikilafarga** [comment]
i'm sorry to join this conversation so late, but have we already settled on using flags as symbols for language toggles?

i would suggest using [language codes](https://en.wikipedia.org/wiki/Language_code) instead, in particular ISO 639-1, so en for English and es for Spanish. official country flags have a lot of geopolitical baggage that languages should be less restricted by, imo.

**Comment by vikilafarga** [comment]
oh thank you, i had started to look but didn't happen upon it.

and nah i can work directly with the spanish.js, no problem. we used google sheets that one time precisely because the 4 translators didn't all have direct access to the code like this.

**Comment by vikilafarga** [comment]
i do see that spanish.js and english.js are not identical, but i don't know if this means that english.js has been updated recently or what. can either you or @sofiarm21 confirm?

**Comment by otech47** [comment]
> i do see that spanish.js and english.js are not identical, but i don't know if this means that english.js has been updated recently or what. can either you or @sofiarm21 confirm?

@VikiLafarga consider `english.js` as the master copy and  `spanish.js` should mirror it. The only differences to them should be the translated text. Don't worry about translating the `key` properties those are irrelevant

**Comment by vikilafarga** [comment]
Aight, spanish.js updated. I'm not seeing the changes on the website though, tried hard refreshing and opening in other browsers. Is there some kind of lag?

**Comment by otech47** [comment]
You pushed it to a separate branch right?

**Comment by otech47** [comment]
Oh I see you pushed directly to develop. Only the master branch is linked to the live site. But also avoid pushing directly to master as well. Open up a pull request like this one: https://github.com/setlife-network/website/pull/75

and then when we're sure it's ready we can merge it and it'll auto-deploy

**Comment by vikilafarga** [comment]
Oh I see, okay so that's what I was asking about last week, about whether if I committed it would update the website immediately so I could proofread and make final tweaks after seeing how the text looks and comparing to the original. Or can I preview the website without merging?

**Comment by otech47** [comment]
Ok in that case we can merge to master then since we don't have a test environment set up but it's fine

**Comment by vikilafarga** [comment]
okay thanks!
