### ISSUE TITLE
Design & implement contact form UI

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#6]

**Comment by otech47** [comment]
@sofiarm21 Using the components in the Sketch file that @marinbasic we want to create a contact form with some basic UI elements:

- Text instructions letting the user know that they can enter their email to subscribe for updates from SetLife as we develop our programs
- A text field for the person to enter their email
- A submit button

**Comment by sofiarm21** [comment]
I don't see the form mockup in the sketch file, I will start doing just the basic UI

**Comment by otech47** [comment]
There is no form mockup yet, that's what this issue is meant for. It does need to be designed first, but instead of building it from scratch, we have components in the Sketch file that could be used to create the form. Does that make sense? @sofiarm21

**Comment by sofiarm21** [comment]
yes got it

**Comment by otech47** [comment]
@marinbasic may need some help here with the Contact Form design if you have time. 

This is what we have currently built in React so I think it could use some polishing, but @sofiarm21 will keep focusing on the coding of it to make it functional

<img width="1101" alt="Screen Shot 2019-07-09 at 12 09 31 PM" src="https://user-images.githubusercontent.com/4914611/60916122-77070200-a242-11e9-9b3c-4703a50e1ddc.png">
