### ISSUE TITLE
Add a new page where each past published newsletters can be seen

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#61]
Current format is in markdown so we'll want to implement this in the React app and use the typography design guidelines in the Sketch file created by @marinbasic

## Details on Approach

Steps:
1. Get month string from the URL
2. Read the corresponding file from /content/newsletters that matches the month string
3. setState with the markdown string

Video Walkthough:
https://www.loom.com/share/352866b2b23846e19999e016dcdecf9a

To read the file use: `fs.promises.readFile`
https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fspromises_readfile_path_options

To render the markdown string use: https://github.com/rexxars/react-markdown

**Comment by sofiarm21** [comment]
<img width="1440" alt="Screen Shot 2019-10-26 at 12 49 26 PM" src="https://user-images.githubusercontent.com/49292858/67623096-58c41280-f7ef-11e9-8f01-9ac061a3b68b.png">

**code:**
`const fs = require('fs')`
`const markdownContent = fs.readFileSync(`../content/newletter/${this.props.match.params.month}`)`

**similar issue:**
[https://github.com/jprichardson/node-jsonfile/issues/97](url)

Looks like this has to be done from the server side and then pull the data into the react app. Not the way we had in mind.

**Comment by otech47** [comment]
Hm okay yes I thought maybe this could be a problem, let's change the approach then. On your end, set it up as if you are fetching from the API:

```
import { API_ROOT } from '../constants'

fetch(`${API_ROOT}/fetchNewsletter/${month}`)
.then(response => {
    const markdownContent = response
    ...
})
```

I'll open another issue for setting up that endpoint on the backend so we can serve the files up that way
