### ISSUE TITLE
Update About Us section

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#70]
- [x] Add Dave Corkle, Director
- [x] Add Sofia's testimonial
- [x] Upload images to GitHub (this issue) and change `portrait` values

Updated pic for Quinn:
![qp](https://user-images.githubusercontent.com/4914611/68456387-e7785c80-01fd-11ea-91ee-14dec845c871.jpeg)

**Comment by sofiarm21** [comment]
images:

- Oscar Lafarga
![OscarLafargaProfilePhoto](https://user-images.githubusercontent.com/49292858/68433886-0808ce00-018e-11ea-9818-64cd4372bdc6.png)
-Viki Lafarga
![VikiLafargaProfilePhoto](https://user-images.githubusercontent.com/49292858/68434040-5fa73980-018e-11ea-9ab5-079506b65ad2.jpg)
-Rebeca Rubio
![RebecaProfilePicture](https://user-images.githubusercontent.com/49292858/68434144-a6952f00-018e-11ea-9fcd-b00218b98c64.png)
-David Lafarga
<img width="180" alt="DavidLafargaProfilePhoto" src="https://user-images.githubusercontent.com/49292858/68434298-ff64c780-018e-11ea-98ad-56d68c3275b4.png">
-Marin Basic
![MarinBasicProfilePhoto](https://user-images.githubusercontent.com/49292858/68434644-dbee4c80-018f-11ea-9630-9f2ff85d9325.jpeg)
-Sofia Rodriguez
<img width="347" alt="SofiaRodriguezProfilePhoto" src="https://user-images.githubusercontent.com/49292858/68435380-8ca91b80-0191-11ea-9501-2668bb0dcd36.png">

**Comment by sofiarm21** [comment]
-Quinn Pruitt
![QuinnProfilePicture](https://user-images.githubusercontent.com/49292858/68435838-badb2b00-0192-11ea-8037-e1a1f931b022.jpg)
-Marin Basic 
![MarinBasicProfilePhoto](https://user-images.githubusercontent.com/49292858/68434644-dbee4c80-018f-11ea-9630-9f2ff85d9325.jpeg)

**Comment by sofiarm21** [comment]
- Quinn Pruitt
![Quinn](https://user-images.githubusercontent.com/49292858/68627489-41a24780-04b4-11ea-87d4-e3a73ff96d5c.jpeg)

**Comment by otech47** [comment]
- [ ] Add testimonial for Rebeca

@rebecarubio

**Comment by otech47** [comment]
One more task added today for this so reopening until @rebecarubio has added her testimonial. @rebecarubio if you like maybe post what you want here and @sofiarm21 can take care of it if you're busy with other projects

**Comment by rebecarubio** [comment]
Yes, I'm gonna do that. For now I only have the testimonial in Spanish but I will try to translate it in English soon, or I'll appreciate the help if @vikilafarga can take a look on this.

"El programa de mentoría de SetLife me ha permitido consolidar mis conocimientos de programación colaborando de forma directa en su desarrollo. El uso de nuevas herramientas y de software actual me han hecho evolucionar rápidamente y adquirir mejores prácticas de implementación de código y de comunicación a la hora de colaborar con otras personas dentro de un mismo proyecto. 
Como desarrolladora de software he cumplido uno de mis objetivos: poner en práctica aquellos conocimientos que quedan sin profundizar en el aula gracias a la metodología del aprendizaje basado en proyectos. Actualmente mis habilidades tecnológicas siguen evolucionando de una forma más efectiva y en un ambiente de trabajo que estimula la autonomía y el crecimiento profesional.”

**Comment by sofiarm21** [comment]
- Dave Corkle
![DaveCorkle](https://user-images.githubusercontent.com/49292858/70638445-453e0100-1c0f-11ea-91c1-24f5612ce1df.jpg)
