### ISSUE TITLE
Polish UI and optimize responsiveness

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#79]
- Perform some more responsiveness testing on tablet size devices 
- Match the site side by side to the Sketch file and implement details in spacing and typography

All sizes
- [x] Bold titles on ProgramCards
- [x] Arrow on ProgramCard should be blue
- [x] Bold titles on CoreValues
- [x] Reduce whitespace above and below Quote section by  ~50%

Mobile
- [x] Fix spacing on divider line between TeaserTiles
![Screen Shot 2019-11-15 at 7 55 22 PM](https://user-images.githubusercontent.com/4914611/68968046-ea68e380-07e1-11ea-9c78-887a519f466a.png)
- [x] Fix wraparound of arrow icon on TeaserTiles and ProgramCards
![Screen Shot 2019-11-15 at 8 03 05 PM](https://user-images.githubusercontent.com/4914611/68968493-f903ca80-07e2-11ea-92df-69644f70e11d.png)
- [x] Fix wraparound of arrow icon and title on CoreValues
![Screen Shot 2019-11-15 at 8 04 33 PM](https://user-images.githubusercontent.com/4914611/68968572-3405fe00-07e3-11ea-81fb-16a4ee86074e.png)
![Screen Shot 2019-11-15 at 8 04 29 PM](https://user-images.githubusercontent.com/4914611/68968574-349e9480-07e3-11ea-8f0c-c93b898db48f.png)
- [x] Fix horizontal scrolling overflow issue (`overflow-x: hidden` might be an easy fix)
- [x] Center Tech Careers text content
![Screen Shot 2019-11-15 at 8 06 17 PM](https://user-images.githubusercontent.com/4914611/68968654-6adc1400-07e3-11ea-86ae-92aa205fa574.png)
- [x] Fix padding/margin alignment of Newsletter to Quote sections
![Screen Shot 2019-11-15 at 8 07 37 PM 1](https://user-images.githubusercontent.com/4914611/68968784-b55d9080-07e3-11ea-8588-022a2eee1ad7.png)

Desktop
- [x] Align baseline of "People over profit" with baseline of setlife logo text in Header
- [x] Center-align and bolden the navigation items in the Header with the Translate dropdown
- [x] Check all instances of `Title` to match sizes with h1/h2/h3 system in Sketch
- [x] Center align arrow with text in `TeaserTile` and `ProgramCard`
- [x] Fix vertical spacing on `Headline` inside `Programs`
![Screen Shot 2019-11-15 at 7 59 00 PM](https://user-images.githubusercontent.com/4914611/68968267-6a8f4900-07e2-11ea-8713-c513839546ad.png)
- [x] Vertical distance should be equal to horizontal distance between ProgramCards
![Screen Shot 2019-11-15 at 8 01 49 PM](https://user-images.githubusercontent.com/4914611/68968440-d376c100-07e2-11ea-8c76-fc1ecb095e73.png)

Tablet (portrait)
- [x] Allow a flexible height for text content in TeaserTile without breaking any other screen sizes

Reference:
https://www.loom.com/share/3c886aa9aec84d9f911d0d0f3a026a50

**Comment by sofiarm21** [comment]
- [ ] Keep only text component

**Comment by sofiarm21** [comment]
All sizes:

- [ ] convert consultation alignment issue to boostrap classes instead of window width

mobile:

- [ ] Fix consultation height 
<img width="696" alt="Screen Shot 2019-11-29 at 2 55 17 PM" src="https://user-images.githubusercontent.com/49292858/69901817-f2d22a00-135c-11ea-8e46-3cf8f892078e.png">
-[ ] Make Programs line shorter

<img width="409" alt="Screen Shot 2019-11-29 at 2 37 10 PM" src="https://user-images.githubusercontent.com/49292858/69901832-19906080-135d-11ea-8b57-35b465657d03.png">
