### ISSUE TITLE
Implement designed welcome email

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#86]
@sofiarm21 upload design here

**Comment by sofiarm21** [comment]
https://drive.google.com/drive/folders/1CXVjtO-dHXMB4JQElkHG9KMvXKQvNMLx

**Comment by otech47** [comment]
Should include a button that links to the unsubscribe API endpoint implemented in #85

**Comment by otech47** [comment]
# Details
https://www.loom.com/share/aa2ae18b9aad4b5cbc5920a6303fd526

**Comment by sofiarm21** [comment]
![emailimg](https://user-images.githubusercontent.com/49292858/70641401-f34baa00-1c13-11ea-84c0-fe4d1c62b0e7.png)

**Comment by sofiarm21** [comment]
![Logo](https://user-images.githubusercontent.com/49292858/70749413-aeeb0780-1d02-11ea-8c75-5a1238df212b.png)

**Comment by otech47** [comment]
![Screen Shot 2019-12-13 at 2 01 15 PM](https://user-images.githubusercontent.com/4914611/70825109-a43b7b80-1db1-11ea-8919-2ab4298c1cc8.png)
![Screen Shot 2019-12-13 at 2 04 57 PM](https://user-images.githubusercontent.com/4914611/70825108-a43b7b80-1db1-11ea-9161-c21d09f00526.png)

**Comment by sofiarm21** [comment]
The email grid renders correctly .
The unsubscribe link uses the id as expected, but the link doesn't work, like the unsubscribe function it's never called, but the endpoint it's correct.

**Comment by otech47** [comment]
> The email grid renders correctly .
> The unsubscribe link uses the id as expected, but the link doesn't work, like the unsubscribe function it's never called, but the endpoint it's correct.

It seems you won't be able to test this the way it is anyway since you hardcode the `href` to www.setlife.network. When you click on that link, it would go try and run on the live site, which doesn't have these changes deployed yet and wouldn't run anything. You would need it to be `http://localhost:4000/api/unsubscribe/:id` in order to expect the function to run the logs in your console.

If you confirm it works locally obviously we need to keep it on the live site before we deploy, but ideally you could even replace it with an environment variable instead of hardcoding it so we don't have to manually switch back and forth between testing in development and testing live. (same logic that is done on the frontend to figure out which URL to make API requests to: https://github.com/setlife-network/website/blob/d892dc5b098d829c16a06b67129ad5661f71061d/src/constants.js#L1)

**Comment by sofiarm21** [comment]
bug
<img width="1408" alt="Screen Shot 2019-12-18 at 3 17 40 PM" src="https://user-images.githubusercontent.com/49292858/71299126-1425a500-2362-11ea-9021-c3f173eb53b2.png">

reproduces every time the unsubscribeUser function is called
when I console log `done` the result is `{ }`
