### ISSUE TITLE
Tweak UI for newsletters 

### ISSUE THREAD

**Issue by otech47** [setlife-network/website#95]
- [x] Sort the list of newsletters in chronological order with the most recent at the top and instead of showing the filename with `.md` extension, just show the month and year of like `January 2019` (the [moment library](https://momentjs.com/docs/#/displaying/format/) should be quite helpful for this 
![Screenshot_20191211-101618](https://user-images.githubusercontent.com/4914611/70634021-7f9fa200-1bff-11ea-8473-06a88839531c.jpg)

- [x] On each actual newsletter page, padding/margins on mobile are too big and squish the content too much. We can use this white space better 
![Screenshot_20191211-101629](https://user-images.githubusercontent.com/4914611/70634442-3b60d180-1c00-11ea-9d8f-d0a1ee2eecc2.jpg)

**Comment by sofiarm21** [comment]
This is how I managed to order the months:

<img width="1085" alt="Screen Shot 2019-12-22 at 12 05 54 AM" src="https://user-images.githubusercontent.com/49292858/71316908-e702f080-244e-11ea-905b-641d13abed73.png">

There should be a more logical way to do this since this is really hard coded
